import type { components } from '@/api/generated/types'

// Use autogenerated types from the backend
export type User = components['schemas']['UserRead']
export type MusicAnalysisResponse = components['schemas']['MusicAnalysisResponse']

export interface AuthState {
  user: User | null
  isAuthenticated: boolean
  isLoading: boolean
  error: string | null
}

export interface AuthContextType extends AuthState {
  login: () => Promise<void>
  logout: () => void
  refreshUser: () => Promise<void>
}

export interface LoginResponse {
  access_token: string
  token_type: string
  user: User
}

export interface SpotifyAuthResponse {
  authorization_url: string
}
