import { tokenService } from '../tokens/tokenService'
import type { components } from '@/api/generated/types'

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'https://127.0.0.1:8443'

// Use autogenerated types
type UserRead = components['schemas']['UserRead']
type MusicAnalysisResponse = components['schemas']['MusicAnalysisResponse']
type BeginAnalysisResponse = components['schemas']['BeginAnalysisResponse']
type AnalysisStatusResponse = components['schemas']['AnalysisStatusResponse']

class ApiError extends Error {
  constructor(
    message: string,
    public status: number,
    public response?: Record<string, unknown>
  ) {
    super(message)
    this.name = 'ApiError'
  }
}

export class AuthenticatedApiClient {
  private baseUrl: string

  constructor(baseUrl: string = API_BASE_URL) {
    this.baseUrl = baseUrl
  }

  private async request<T>(
    endpoint: string,
    options: RequestInit = {}
  ): Promise<T> {
    const token = tokenService.getToken()

    const config: RequestInit = {
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...(token && { Authorization: `Bearer ${token}` }),
        ...options.headers,
      },
    }

    const response = await fetch(`${this.baseUrl}${endpoint}`, config)

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}))
      throw new ApiError(
        errorData.detail || 'An error occurred',
        response.status,
        errorData
      )
    }

    return response.json()
  }

  // Auth endpoints using autogenerated types
  async getCurrentUser(): Promise<UserRead> {
    return this.request<UserRead>('/api/v1/auth/me')
  }

  async getSpotifyAuthUrl(): Promise<{ authorization_url: string }> {
    return this.request<{ authorization_url: string }>('/api/v1/auth/login')
  }

  async handleAuthCallback(code: string, state: string): Promise<{ access_token: string; token_type: string; user: UserRead }> {
    return this.request('/api/v1/auth/callback', {
      method: 'POST',
      body: JSON.stringify({ code, state }),
    })
  }

  async logout(): Promise<{ message: string }> {
    return this.request('/api/v1/auth/logout', { method: 'POST' })
  }

  // Music analysis endpoints using autogenerated types
  async beginAnalysis(): Promise<BeginAnalysisResponse> {
    return this.request<BeginAnalysisResponse>('/api/v1/music/analysis/begin', {
      method: 'POST'
    })
  }

  async pollAnalysisStatus(): Promise<AnalysisStatusResponse> {
    return this.request<AnalysisStatusResponse>('/api/v1/music/analysis/status')
  }

  async getAnalysisResult(): Promise<MusicAnalysisResponse> {
    return this.request<MusicAnalysisResponse>('/api/v1/music/analysis/result')
  }

  async getLatestAnalysis(): Promise<MusicAnalysisResponse | null> {
    return this.request<MusicAnalysisResponse | null>('/api/v1/music/analysis/latest')
  }

  // Legacy endpoint (for backward compatibility)
  async analyzeMusic(): Promise<MusicAnalysisResponse> {
    return this.request<MusicAnalysisResponse>('/api/v1/music/analyze', {
      method: 'POST'
    })
  }
}

export const apiClient = new AuthenticatedApiClient()
