import type { components } from '@/api/generated/types'

// Use autogenerated types from the backend
export type MusicAnalysisResponse = components['schemas']['MusicAnalysisResponse']
export type BeginAnalysisResponse = components['schemas']['BeginAnalysisResponse']
export type AnalysisStatusResponse = components['schemas']['AnalysisStatusResponse']
export type AnalysisStatus = components['schemas']['AnalysisStatus']
export type PublicAnalysisResponse = components['schemas']['PublicAnalysisResponse']

// Frontend-specific types (not from backend)
export interface AnalysisRequest {
  timeRange: 'short_term' | 'medium_term' | 'long_term'
  includeRecentTracks: boolean
  includeTopArtists: boolean
  includeTopGenres: boolean
  includePlaylistAnalysis: boolean
}

// Spotify API types (for future use)
export interface SpotifyImage {
  url: string
  height: number | null
  width: number | null
}

export interface Track {
  id: string
  name: string
  artists: Artist[]
  album: Album
  popularity: number
  duration_ms: number
  explicit: boolean
  external_urls: {
    spotify: string
  }
}

export interface Artist {
  id: string
  name: string
  genres: string[]
  popularity: number
  external_urls: {
    spotify: string
  }
}

export interface Album {
  id: string
  name: string
  artists: Artist[]
  release_date: string
  total_tracks: number
  external_urls: {
    spotify: string
  }
  images: SpotifyImage[]
}
